// Central config. Generated by `node scripts/setup.js` (run it once after install).
// config.json lives at the project root and is gitignored — it holds per-user secrets.
const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'config.json');

const DEFAULTS = {
  port: 3000,
  dashboard_password: null, // required — setup.js generates it
  digest: {
    enabled: true,
    hour: 18,             // local hour of day the daily digest is sent
    lookback_hours: 24,   // how far back to scan for unanswered chats
    stale_hours: 3,       // inbound msg older than this without reply = "possibly missed"
    max_drafts: 5,        // max chats to generate reply drafts for (via claude -p)
    include_groups: false // groups are noisy; DMs only by default
  },
  health: {
    autoheal_interval_min: 5 // retry dropped accounts forever, every N minutes
  }
};

function load() {
  let user = {};
  try {
    user = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
  } catch {
    // No config yet — server refuses to start without a password (see web/server.js).
  }
  return {
    ...DEFAULTS,
    ...user,
    digest: { ...DEFAULTS.digest, ...(user.digest || {}) },
    health: { ...DEFAULTS.health, ...(user.health || {}) },
  };
}

module.exports = { config: load(), CONFIG_PATH };
